In [ ]:
"""
Document Indexing Pipeline for Hybrid Search

This notebook builds the retrieval indexes used by the HybridSearchAgent:
  - Chroma vector store  : stores OpenAI-embedded document chunks for semantic search
  - SQLite FTS5 index    : stores raw chunk text for keyword (full-text) search

Workflow
--------
1. Load documents (.txt, .pdf, .docx) from the `documents/` directory.
2. Build a Pandas DataFrame to inspect and optionally enrich document-level metadata
   (filename, folder, file type, word/char counts, custom categories, timestamps).
3. Persist the DataFrame as CSV for reproducibility.
4. Convert back to LangChain Documents and split into overlapping chunks.
5. Annotate chunks with positional metadata (chunk_id, chunk_start_char, chunk_end_char).
6. Validate and standardize chunk metadata with a Pydantic model.
7. Embed chunks and upsert into Chroma.
8. Populate the SQLite FTS5 table used by the full-text search layer.
9. PCA visualization of the resulting embedding space (optional, 2-D scatter plot).

Run the cells top-to-bottom on first use; re-run individual sections to
refresh either index after document changes.
"""

In [1]:
# Standard library
import hashlib
import os
from datetime import datetime, timezone

# Third-party
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from dotenv import load_dotenv
from langchain_chroma import Chroma
from langchain_community.document_loaders import DirectoryLoader, TextLoader, PyPDFLoader, Docx2txtLoader
from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langdetect import DetectorFactory, detect
from sklearn.decomposition import PCA

# Local imports
from fts_search import FTSStore
from pydantic_models import ChunkMetadata

# Make langdetect deterministic across runs.
DetectorFactory.seed = 0

# Load env from specific path.
load_dotenv("C:/Users/kjosi/dotenv/.env")

True

### LOAD DOCUMENTS AND CREATE PANDAS DATAFRAME

In [2]:
# Load documents with DirectoryLoader - loads multiple files from a specified directory into LangChain Document objects
txt_loader = DirectoryLoader("./documents", glob="**/*.txt", loader_cls=TextLoader)
pdf_loader = DirectoryLoader("./documents", glob="**/*.pdf", loader_cls=PyPDFLoader)
docx_loader = DirectoryLoader("./documents", glob="**/*.docx", loader_cls=Docx2txtLoader)

documents = txt_loader.load() + pdf_loader.load() + docx_loader.load()
print(f"Loaded {len(documents)} documents")

Loaded 11 documents

In [3]:
# Print one of the documents
print(documents[0])

page_content='Norway is a Scandinavian country located in Northern Europe, known for its dramatic landscapes and high quality of life.
It has a population of around 5.5 million people and a capital city called Oslo.
The country is famous for its fjords, mountains, and northern lights, which attract visitors from all over the world.

Norway consistently ranks high in global happiness and human development indexes.
It has a strong welfare system, free education, and universal healthcare.
The official language is Norwegian, and the country has two written forms: BokmÃ¥l and Nynorsk.

Fishing, shipping, and energy production are key industries.
Norway is also one of the world's largest exporters of oil and gas.
Despite its wealth, it is committed to sustainability and renewable energy development.' metadata={'source': 'documents\\norway_facts.txt'}

In [4]:
# Create pandas dataframe from documents and metadata
rows = []
for doc in documents:
    rows.append({
        "text": doc.page_content,
        **doc.metadata
    })

df = pd.DataFrame(rows)
df.head(2)

,text,source,producer,creator,creationdate,author,keywords,moddate,subject,title,trapped,total_pages,page,page_label
0,Norway is a Scandinavian country located in No...,documents\norway_facts.txt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Norway is full of interesting and fun facts th...,documents\norway_fun_facts.pdf,ReportLab PDF Library - (opensource),(unspecified),2026-03-24T09:20:12+00:00,(anonymous),,2026-03-24T09:20:12+00:00,(unspecified),(anonymous),/False,1.0,0.0,1

### OPTIONS FOR ADDING METADATA

In [ ]:
## EITHER: REQUIRED STEP — KEEP "text" and "source"
# Template for dropping unwanted columns. Edit the list to name the actual
# columns you want removed, then uncomment the line below to run it.
# Either run this cell OR the next one — they are mutually exclusive paths.
# df = df.drop(["col_to_drop_1", "col_to_drop_2"], axis=1)
df.head(2)

In [5]:
## OR: REQUIRED STEP — KEEP "text" and "source"
# Whitelist approach: keep only "text" and "source", discard everything else.
# Either run this cell OR the previous one — they are mutually exclusive paths.
df = df[["text", "source"]]
df.head(2)

,text,source
0,Norway is a Scandinavian country located in No...,documents\norway_facts.txt
1,Norway is full of interesting and fun facts th...,documents\norway_fun_facts.pdf

In [6]:
## REQUIRED STEP
# Add unique document IDs based on the document text itself
df['doc_hash_id'] = df['text'].apply(lambda x: hashlib.md5(x.encode()).hexdigest())
df.head(2)

,text,source,doc_hash_id
0,Norway is a Scandinavian country located in No...,documents\norway_facts.txt,8106bcb4bb84ca02dd797d61f0e09ae2
1,Norway is full of interesting and fun facts th...,documents\norway_fun_facts.pdf,12757987f740b484a9ff5e97e95b0358

In [7]:
# Add filename from source path
df["filename"] = df["source"].apply(lambda x: os.path.basename(x))
df.head(2)

,text,source,doc_hash_id,filename
0,Norway is a Scandinavian country located in No...,documents\norway_facts.txt,8106bcb4bb84ca02dd797d61f0e09ae2,norway_facts.txt
1,Norway is full of interesting and fun facts th...,documents\norway_fun_facts.pdf,12757987f740b484a9ff5e97e95b0358,norway_fun_facts.pdf

In [8]:
# Add file type
df["file_type"] = df["filename"].apply(lambda x: os.path.splitext(x)[-1])
df.head(2)

,text,source,doc_hash_id,filename,file_type
0,Norway is a Scandinavian country located in No...,documents\norway_facts.txt,8106bcb4bb84ca02dd797d61f0e09ae2,norway_facts.txt,.txt
1,Norway is full of interesting and fun facts th...,documents\norway_fun_facts.pdf,12757987f740b484a9ff5e97e95b0358,norway_fun_facts.pdf,.pdf

In [9]:
# Add folder name from source path
df["folder"] = df["source"].apply(lambda x: os.path.dirname(x))
df.head(2)

,text,source,doc_hash_id,filename,file_type,folder
0,Norway is a Scandinavian country located in No...,documents\norway_facts.txt,8106bcb4bb84ca02dd797d61f0e09ae2,norway_facts.txt,.txt,documents
1,Norway is full of interesting and fun facts th...,documents\norway_fun_facts.pdf,12757987f740b484a9ff5e97e95b0358,norway_fun_facts.pdf,.pdf,documents

In [10]:
# Add text length
df["doc_char_count"] = df["text"].apply(len)
df.head(2)

,text,source,doc_hash_id,filename,file_type,folder,doc_char_count
0,Norway is a Scandinavian country located in No...,documents\norway_facts.txt,8106bcb4bb84ca02dd797d61f0e09ae2,norway_facts.txt,.txt,documents,796
1,Norway is full of interesting and fun facts th...,documents\norway_fun_facts.pdf,12757987f740b484a9ff5e97e95b0358,norway_fun_facts.pdf,.pdf,documents,802

In [11]:
# Add word count
df["doc_word_count"] = df["text"].apply(lambda x: len(x.split()))
df.head(2)

,text,source,doc_hash_id,filename,file_type,folder,doc_char_count,doc_word_count
0,Norway is a Scandinavian country located in No...,documents\norway_facts.txt,8106bcb4bb84ca02dd797d61f0e09ae2,norway_facts.txt,.txt,documents,796,123
1,Norway is full of interesting and fun facts th...,documents\norway_fun_facts.pdf,12757987f740b484a9ff5e97e95b0358,norway_fun_facts.pdf,.pdf,documents,802,132

In [12]:
## REQUIRED STEP
# Add ingestion timestamp
df["ingested_at"] = int(datetime.now(timezone.utc).timestamp())
df.head(2)

,text,source,doc_hash_id,filename,file_type,folder,doc_char_count,doc_word_count,ingested_at
0,Norway is a Scandinavian country located in No...,documents\norway_facts.txt,8106bcb4bb84ca02dd797d61f0e09ae2,norway_facts.txt,.txt,documents,796,123,1777965070
1,Norway is full of interesting and fun facts th...,documents\norway_fun_facts.pdf,12757987f740b484a9ff5e97e95b0358,norway_fun_facts.pdf,.pdf,documents,802,132,1777965070

In [13]:
# Add category - example: "finance" - under dev (match/switch case) - under development !!
def classify_doc(text):
    if "norway" in text.lower():
        return "Norway"
    return "other"

df["category"] = df["text"].apply(classify_doc)
df.head(2)

,text,source,doc_hash_id,filename,file_type,folder,doc_char_count,doc_word_count,ingested_at,category
0,Norway is a Scandinavian country located in No...,documents\norway_facts.txt,8106bcb4bb84ca02dd797d61f0e09ae2,norway_facts.txt,.txt,documents,796,123,1777965070,Norway
1,Norway is full of interesting and fun facts th...,documents\norway_fun_facts.pdf,12757987f740b484a9ff5e97e95b0358,norway_fun_facts.pdf,.pdf,documents,802,132,1777965070,Norway

In [14]:
# Add language
df['language'] = df['text'].apply(lambda x: detect(x) if x.strip() else 'unknown')
df.head(2)

,text,source,doc_hash_id,filename,file_type,folder,doc_char_count,doc_word_count,ingested_at,category,language
0,Norway is a Scandinavian country located in No...,documents\norway_facts.txt,8106bcb4bb84ca02dd797d61f0e09ae2,norway_facts.txt,.txt,documents,796,123,1777965070,Norway,en
1,Norway is full of interesting and fun facts th...,documents\norway_fun_facts.pdf,12757987f740b484a9ff5e97e95b0358,norway_fun_facts.pdf,.pdf,documents,802,132,1777965070,Norway,en

In [ ]:
## OPTIONAL STEP - under development !!
# Add short summary
def generate_summary(text):
    # Call an LLM 
    # Or just take the first 100 characters as a 'mini-summary'
    return f"Snippet about: {text[:100]}..."

df['summary'] = df['text'].apply(generate_summary)
df.head(2)

In [ ]:
## OPTIONAL STEP - under development !!
# Add content type
def classify_content(text: str) -> str:
    # 1. Check for Tables (look for common markers like pipes or many tabs)
    if "|" in text or text.count("\t") > 3:
        return "table"
    # 2. Check for Headers (Short, usually no ending period, often bold/caps)
    if len(text) < 120 and not text.strip().endswith('.'):
        return "header"
    # 3. Default
    return "text"

# Apply to the document-level DataFrame.  The text column is "text"
# (set in the DataFrame-creation cell above); chunk-level page_content
# does not exist at this stage of the pipeline.
df['content_type'] = df['text'].apply(classify_content)
df.head(2)

In [15]:
## OPTIONAL STEP
# Save df for temporary storage as csv, save for reproducibility
df.to_csv("documents_with_metadata_df.csv", index=False)

# Load file later
df = pd.read_csv("documents_with_metadata_df.csv")

### CONVERT BACK FROM PANDAS DATAFRAME TO DOCUMENTS

In [16]:
# Convert back to LangChain Document objects with metadata
documents_with_metadata = []

for _, row in df.iterrows():
    metadata = row.drop("text").to_dict()

    documents_with_metadata.append(
        Document(
            page_content=row["text"],
            metadata=metadata
        )
    )

print(f"Loaded {len(documents_with_metadata)} documents")

Loaded 11 documents

In [17]:
# Print one of the documents
print(documents_with_metadata[0])

page_content='Norway is a Scandinavian country located in Northern Europe, known for its dramatic landscapes and high quality of life.
It has a population of around 5.5 million people and a capital city called Oslo.
The country is famous for its fjords, mountains, and northern lights, which attract visitors from all over the world.

Norway consistently ranks high in global happiness and human development indexes.
It has a strong welfare system, free education, and universal healthcare.
The official language is Norwegian, and the country has two written forms: BokmÃ¥l and Nynorsk.

Fishing, shipping, and energy production are key industries.
Norway is also one of the world's largest exporters of oil and gas.
Despite its wealth, it is committed to sustainability and renewable energy development.' metadata={'source': 'documents\\norway_facts.txt', 'doc_hash_id': '8106bcb4bb84ca02dd797d61f0e09ae2', 'filename': 'norway_facts.txt', 'file_type': '.txt', 'folder': 'documents', 'doc_char_count': 796, 'doc_word_count': 123, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en'}

In [ ]:
## OPTIONAL STEP
# If small tweaks are needed, change metadata after document creation, example: category
for doc in documents_with_metadata:
    doc.metadata["category"] = "new_value"

### CREATE CHUNKS AND ADD CHUNK METADATA

In [18]:
# Split documents into chunks.  `add_start_index=True` asks LangChain to
# stamp each chunk with a per-document `start_index` (character offset
# within its source document).  This is the correct, overlap-aware
# offset; we map it to chunk_start_char in a later cell.
splitter = RecursiveCharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50,
    add_start_index=True,
)

chunks = splitter.split_documents(documents_with_metadata)

In [19]:
# Print chunk metadata
for i, chunk in enumerate(chunks):
    print(chunk.metadata)

{'source': 'documents\\norway_facts.txt', 'doc_hash_id': '8106bcb4bb84ca02dd797d61f0e09ae2', 'filename': 'norway_facts.txt', 'file_type': '.txt', 'folder': 'documents', 'doc_char_count': 796, 'doc_word_count': 123, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 0}
{'source': 'documents\\norway_facts.txt', 'doc_hash_id': '8106bcb4bb84ca02dd797d61f0e09ae2', 'filename': 'norway_facts.txt', 'file_type': '.txt', 'folder': 'documents', 'doc_char_count': 796, 'doc_word_count': 123, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 204}
{'source': 'documents\\norway_facts.txt', 'doc_hash_id': '8106bcb4bb84ca02dd797d61f0e09ae2', 'filename': 'norway_facts.txt', 'file_type': '.txt', 'folder': 'documents', 'doc_char_count': 796, 'doc_word_count': 123, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 323}
{'source': 'documents\\norway_facts.txt', 'doc_hash_id': '8106bcb4bb84ca02dd797d61f0e09ae2', 'filename': 'norway_facts.txt', 'file_type': '.txt', 'folder': 'documents', 'doc_char_count': 796, 'doc_word_count': 123, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 578}
{'source': 'documents\\norway_fun_facts.pdf', 'doc_hash_id': '12757987f740b484a9ff5e97e95b0358', 'filename': 'norway_fun_facts.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 802, 'doc_word_count': 132, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 0}
{'source': 'documents\\norway_fun_facts.pdf', 'doc_hash_id': '12757987f740b484a9ff5e97e95b0358', 'filename': 'norway_fun_facts.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 802, 'doc_word_count': 132, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 285}
{'source': 'documents\\norway_fun_facts.pdf', 'doc_hash_id': '12757987f740b484a9ff5e97e95b0358', 'filename': 'norway_fun_facts.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 802, 'doc_word_count': 132, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 573}
{'source': 'documents\\norway_population.pdf', 'doc_hash_id': 'a85a7b772c14f8bd1a6c5f1c4cd4a9d6', 'filename': 'norway_population.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 805, 'doc_word_count': 122, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 0}
{'source': 'documents\\norway_population.pdf', 'doc_hash_id': 'a85a7b772c14f8bd1a6c5f1c4cd4a9d6', 'filename': 'norway_population.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 805, 'doc_word_count': 122, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 213}
{'source': 'documents\\norway_population.pdf', 'doc_hash_id': 'a85a7b772c14f8bd1a6c5f1c4cd4a9d6', 'filename': 'norway_population.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 805, 'doc_word_count': 122, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 436}
{'source': 'documents\\norway_population.pdf', 'doc_hash_id': 'a85a7b772c14f8bd1a6c5f1c4cd4a9d6', 'filename': 'norway_population.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 805, 'doc_word_count': 122, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 652}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 0}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 109}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 354}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 527}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 776}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1023}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1119}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1165}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1420}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1539}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1791}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 2076}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 2111}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 2368}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 2617}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 2740}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 2799}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 3046}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 3293}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 3342}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 3595}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 3846}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 3973}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 4245}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 0}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 94}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 343}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 451}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 700}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 949}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1068}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1097}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1347}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1403}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1653}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1836}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 2100}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 2307}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 2598}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 2783}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 3033}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 3254}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 3480}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 3649}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 3881}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 4161}
{'source': 'documents\\norway_famous_norwegians.docx', 'doc_hash_id': '28060fa03b3f9be8e621b0ea4f5a67cf', 'filename': 'norway_famous_norwegians.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 3929, 'doc_word_count': 586, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 0}
{'source': 'documents\\norway_famous_norwegians.docx', 'doc_hash_id': '28060fa03b3f9be8e621b0ea4f5a67cf', 'filename': 'norway_famous_norwegians.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 3929, 'doc_word_count': 586, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 268}
{'source': 'documents\\norway_famous_norwegians.docx', 'doc_hash_id': '28060fa03b3f9be8e621b0ea4f5a67cf', 'filename': 'norway_famous_norwegians.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 3929, 'doc_word_count': 586, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 561}
{'source': 'documents\\norway_famous_norwegians.docx', 'doc_hash_id': '28060fa03b3f9be8e621b0ea4f5a67cf', 'filename': 'norway_famous_norwegians.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 3929, 'doc_word_count': 586, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 817}
{'source': 'documents\\norway_famous_norwegians.docx', 'doc_hash_id': '28060fa03b3f9be8e621b0ea4f5a67cf', 'filename': 'norway_famous_norwegians.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 3929, 'doc_word_count': 586, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'start_index': 1101}

In [ ]:
# Print specific chunk metadata, example: source
for i, chunk in enumerate(chunks):
    print(chunk.metadata["source"])

In [20]:
## REQUIRED STEP
# Add chunk_id (per-document, so chunk numbering is stable across re-ingestion).
# Each document's chunks are numbered starting from 0, regardless of load order
# or how many chunks other documents produce.
from collections import defaultdict

chunk_counter = defaultdict(int)
for chunk in chunks:
    doc_hash = chunk.metadata["doc_hash_id"]
    chunk.metadata["chunk_id"] = chunk_counter[doc_hash]
    chunk_counter[doc_hash] += 1

In [21]:
## REQUIRED STEP
# Add chunk_hash_id - unique ID for each chunk based on doc_hash_id + chunk_id.
# Reads chunk_id from the previous cell rather than enumerate, so the hash is
# stable across re-ingestion regardless of corpus load order.
for chunk in chunks:
    chunk_id_string = f"{chunk.metadata['doc_hash_id']}_{chunk.metadata['chunk_id']}"
    chunk.metadata["chunk_hash_id"] = hashlib.md5(chunk_id_string.encode()).hexdigest()

In [ ]:
# Map LangChain's per-document `start_index` (added by `add_start_index=True`
# on the splitter) to metadata fields chunk_start_char and chunk_end_char.
for chunk in chunks:
    start = chunk.metadata.pop("start_index")
    chunk.metadata["chunk_start_char"] = start
    chunk.metadata["chunk_end_char"] = start + len(chunk.page_content)

In [23]:
# Print chunk metadata
for i, chunk in enumerate(chunks):
    print(chunk.metadata)

{'source': 'documents\\norway_facts.txt', 'doc_hash_id': '8106bcb4bb84ca02dd797d61f0e09ae2', 'filename': 'norway_facts.txt', 'file_type': '.txt', 'folder': 'documents', 'doc_char_count': 796, 'doc_word_count': 123, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 0, 'chunk_hash_id': '8b186278d13d3daea0cf22471da897e3', 'chunk_start_char': 0, 'chunk_end_char': 202}
{'source': 'documents\\norway_facts.txt', 'doc_hash_id': '8106bcb4bb84ca02dd797d61f0e09ae2', 'filename': 'norway_facts.txt', 'file_type': '.txt', 'folder': 'documents', 'doc_char_count': 796, 'doc_word_count': 123, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 1, 'chunk_hash_id': 'd25f94855b92240038939a299fa530d0', 'chunk_start_char': 204, 'chunk_end_char': 321}
{'source': 'documents\\norway_facts.txt', 'doc_hash_id': '8106bcb4bb84ca02dd797d61f0e09ae2', 'filename': 'norway_facts.txt', 'file_type': '.txt', 'folder': 'documents', 'doc_char_count': 796, 'doc_word_count': 123, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 2, 'chunk_hash_id': '19f89ab62672ac95e5a89146f4ee88b4', 'chunk_start_char': 323, 'chunk_end_char': 576}
{'source': 'documents\\norway_facts.txt', 'doc_hash_id': '8106bcb4bb84ca02dd797d61f0e09ae2', 'filename': 'norway_facts.txt', 'file_type': '.txt', 'folder': 'documents', 'doc_char_count': 796, 'doc_word_count': 123, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 3, 'chunk_hash_id': 'a6f3cf6f53d2244e06cbb9e973bb1f60', 'chunk_start_char': 578, 'chunk_end_char': 796}
{'source': 'documents\\norway_fun_facts.pdf', 'doc_hash_id': '12757987f740b484a9ff5e97e95b0358', 'filename': 'norway_fun_facts.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 802, 'doc_word_count': 132, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 0, 'chunk_hash_id': '71334a9db47f78209afc7611e8c4f063', 'chunk_start_char': 0, 'chunk_end_char': 284}
{'source': 'documents\\norway_fun_facts.pdf', 'doc_hash_id': '12757987f740b484a9ff5e97e95b0358', 'filename': 'norway_fun_facts.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 802, 'doc_word_count': 132, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 1, 'chunk_hash_id': '53f60b18b53f6b3b453e1610393dfa4a', 'chunk_start_char': 285, 'chunk_end_char': 582}
{'source': 'documents\\norway_fun_facts.pdf', 'doc_hash_id': '12757987f740b484a9ff5e97e95b0358', 'filename': 'norway_fun_facts.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 802, 'doc_word_count': 132, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 2, 'chunk_hash_id': 'ef2281c25da89547e5a07a4a44ae6eba', 'chunk_start_char': 573, 'chunk_end_char': 802}
{'source': 'documents\\norway_population.pdf', 'doc_hash_id': 'a85a7b772c14f8bd1a6c5f1c4cd4a9d6', 'filename': 'norway_population.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 805, 'doc_word_count': 122, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 0, 'chunk_hash_id': '22fa65e171feb70ffef7b78045ec61b5', 'chunk_start_char': 0, 'chunk_end_char': 254}
{'source': 'documents\\norway_population.pdf', 'doc_hash_id': 'a85a7b772c14f8bd1a6c5f1c4cd4a9d6', 'filename': 'norway_population.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 805, 'doc_word_count': 122, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 1, 'chunk_hash_id': 'ea196627d4c85248cdd6d698226959a2', 'chunk_start_char': 213, 'chunk_end_char': 435}
{'source': 'documents\\norway_population.pdf', 'doc_hash_id': 'a85a7b772c14f8bd1a6c5f1c4cd4a9d6', 'filename': 'norway_population.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 805, 'doc_word_count': 122, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 2, 'chunk_hash_id': 'b4084e678237c7d59f3172eca9be6857', 'chunk_start_char': 436, 'chunk_end_char': 651}
{'source': 'documents\\norway_population.pdf', 'doc_hash_id': 'a85a7b772c14f8bd1a6c5f1c4cd4a9d6', 'filename': 'norway_population.pdf', 'file_type': '.pdf', 'folder': 'documents', 'doc_char_count': 805, 'doc_word_count': 122, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 3, 'chunk_hash_id': '1b2237bdafc43f2e05b465a98d243772', 'chunk_start_char': 652, 'chunk_end_char': 805}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 0, 'chunk_hash_id': '5ccaa85ef9e1d02f559e51e48c92e6ee', 'chunk_start_char': 0, 'chunk_end_char': 107}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 1, 'chunk_hash_id': '30ff498f69898767539dab117566321b', 'chunk_start_char': 109, 'chunk_end_char': 401}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 2, 'chunk_hash_id': '84ef4e6eaf64247ad2cc5cda6ed93a42', 'chunk_start_char': 354, 'chunk_end_char': 525}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 3, 'chunk_hash_id': 'ac4480077d4e117dcf46a671548a8f0b', 'chunk_start_char': 527, 'chunk_end_char': 818}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 4, 'chunk_hash_id': '4a0aa3660a2eefd0baf025c3ffd6a35e', 'chunk_start_char': 776, 'chunk_end_char': 1071}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 5, 'chunk_hash_id': '0946d5e4fa02764fce3781f1523e9de6', 'chunk_start_char': 1023, 'chunk_end_char': 1117}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 6, 'chunk_hash_id': 'c275c37062c5df930120f67b0f9e56d9', 'chunk_start_char': 1119, 'chunk_end_char': 1163}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 7, 'chunk_hash_id': '3f636198c557e4252518bec6b68ce139', 'chunk_start_char': 1165, 'chunk_end_char': 1464}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 8, 'chunk_hash_id': 'e93f1c6567816a3c45eec7d888920df0', 'chunk_start_char': 1420, 'chunk_end_char': 1537}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 9, 'chunk_hash_id': '30255338f25c67d47abd44019fd8d8e0', 'chunk_start_char': 1539, 'chunk_end_char': 1836}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 10, 'chunk_hash_id': 'fab806dfb773bc8a37d2dd1a9316cfbe', 'chunk_start_char': 1791, 'chunk_end_char': 2074}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 11, 'chunk_hash_id': '4151036d8528443a4795963db5899641', 'chunk_start_char': 2076, 'chunk_end_char': 2109}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 12, 'chunk_hash_id': '703d114664e6cee9ff6b12b01b8f55f6', 'chunk_start_char': 2111, 'chunk_end_char': 2409}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 13, 'chunk_hash_id': '1df585cbdc5500ce8300a2667998270a', 'chunk_start_char': 2368, 'chunk_end_char': 2665}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 14, 'chunk_hash_id': '60be03d4d82fd3514b8fce52c0e5f9b8', 'chunk_start_char': 2617, 'chunk_end_char': 2738}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 15, 'chunk_hash_id': '192bd4c61ffc2ac0cd9c8898f4630b79', 'chunk_start_char': 2740, 'chunk_end_char': 2797}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 16, 'chunk_hash_id': '2a886d88bc609ee3d3d95f058b39ec66', 'chunk_start_char': 2799, 'chunk_end_char': 3090}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 17, 'chunk_hash_id': '4edb34d0108f7b14a7c80b3760aef5f7', 'chunk_start_char': 3046, 'chunk_end_char': 3291}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 18, 'chunk_hash_id': 'a940d8e8da92ecadc0f55ae1b6ddb9f8', 'chunk_start_char': 3293, 'chunk_end_char': 3340}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 19, 'chunk_hash_id': '69e4033e4c2fe7560dbea37e9c1cf60e', 'chunk_start_char': 3342, 'chunk_end_char': 3641}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 20, 'chunk_hash_id': 'e27915c3f64b4e3b51982170e1254c40', 'chunk_start_char': 3595, 'chunk_end_char': 3890}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 21, 'chunk_hash_id': 'a5ae47f928c720d705425b4fa2af873f', 'chunk_start_char': 3846, 'chunk_end_char': 3969}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 22, 'chunk_hash_id': '3b0441fa1db30d992545bab3dd06711b', 'chunk_start_char': 3973, 'chunk_end_char': 4243}
{'source': 'documents\\norway_culture_modern_life.docx', 'doc_hash_id': '2771974cd75b247e0933a4452edae492', 'filename': 'norway_culture_modern_life.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4511, 'doc_word_count': 714, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 23, 'chunk_hash_id': '0defb2f63283635b3b9d984ede18075c', 'chunk_start_char': 4245, 'chunk_end_char': 4511}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 0, 'chunk_hash_id': '6fa086ce5eabd83e28a18506422578d2', 'chunk_start_char': 0, 'chunk_end_char': 92}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 1, 'chunk_hash_id': 'e7b61effaa3796a5a84fbe26dbf451cd', 'chunk_start_char': 94, 'chunk_end_char': 388}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 2, 'chunk_hash_id': '26992ff7c0a33d0807ef07a8b2deddea', 'chunk_start_char': 343, 'chunk_end_char': 449}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 3, 'chunk_hash_id': '98bee1ea153f46bcaef18f2426fdeec7', 'chunk_start_char': 451, 'chunk_end_char': 743}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 4, 'chunk_hash_id': 'b5eb50d7c598b3761b29c7a377f69296', 'chunk_start_char': 700, 'chunk_end_char': 997}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 5, 'chunk_hash_id': 'f84ba04fe0decc7f34b6ae9dda2793f2', 'chunk_start_char': 949, 'chunk_end_char': 1066}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 6, 'chunk_hash_id': '0b841aad89c5f47d4acfb0c23b8fe431', 'chunk_start_char': 1068, 'chunk_end_char': 1095}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 7, 'chunk_hash_id': '0f70c7e2b414a63921487a36b5e2bafa', 'chunk_start_char': 1097, 'chunk_end_char': 1396}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 8, 'chunk_hash_id': '11dec306bdd24c72d4687ae5c8c17e46', 'chunk_start_char': 1347, 'chunk_end_char': 1401}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 9, 'chunk_hash_id': '0b56d3ebc2d143b78abba1c0ebc23568', 'chunk_start_char': 1403, 'chunk_end_char': 1697}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 10, 'chunk_hash_id': '3113980a524520aaffbc5342d8a3dbf0', 'chunk_start_char': 1653, 'chunk_end_char': 1834}
{'source': 'documents\\norway_facts.docx', 'doc_hash_id': 'ab4157534cfa3fec97431dcbdf6c3500', 'filename': 'norway_facts.docx', 'file_type': '.docx', 'folder': 'documents', 'doc_char_count': 4355, 'doc_word_count': 666, 'ingested_at': 1777965070, 'category': 'Norway', 'language': 'en', 'chunk_id': 11, 'chunk_hash_id': 'd3faf1d7afe50ee588def96b419c97e4', 'chunk_start_char': 1836, 'chunk_end_char': 2098}

In [ ]:
# Print specific chunk metadata, example: chunk_hash_id
for i, chunk in enumerate(chunks):
    print(chunk.metadata["chunk_hash_id"])

### STANDARDIZE CHUNK METADATA

In [24]:
# Definition to standardize chunk metadata
def standardize_chunk_metadata(chunk):
    """
    Standardizes chunk metadata using Pydantic for type validation.

    Parses metadata into structured fields (e.g., "3" -> 3) based on 
    ChunkMetadata and isolates any remaining extra fields.

    Returns:
        tuple: (original chunk, structured_dict, extra_fields_dict)
    """

    # Explain, example: "chunk_id": "3" > Pydantic converts it > 3 (int)
    std_meta = ChunkMetadata.model_validate(chunk.metadata)

    # model_dump() converts pydantic model into a standard python dict
    structured_metadata = std_meta.model_dump() 

    # Extracts "extra metadata", everything that is NOT in the schema
    extra_metadata = {key: value for key, value in chunk.metadata.items() if key not in structured_metadata}

    return chunk, structured_metadata, extra_metadata

In [25]:
# Run standardize_chunk_metadata() function on all chunks
clean_chunks = []

for chunk in chunks:
    _, structured_metadata, extra_metadata = standardize_chunk_metadata(chunk)

    clean_chunk = chunk.model_copy()
    clean_chunk.metadata = {**structured_metadata, **extra_metadata}

    clean_chunks.append(clean_chunk)

### INGEST CHUNKS: CHROMA DB AND SQLite FTS

> **Re-ingesting after metadata changes.** If a prior run produced stale
> metadata (e.g. old chunk-offset values from before the offset fix), use
> the upsert / refresh cells below with `REFRESH_EXISTING_SOURCES = True`
> rather than the simple-add cells. The simple-add cells are append-only:
> re-running them leaves the old rows in place alongside the new ones,
> producing duplicates and mixing stale and current metadata at retrieval
> time.

In [26]:
# Create / load Chroma DB (persisted locally) — first-time setup only.
# This cell uses `add_documents`, which assigns random UUIDs as Chroma
# IDs.  Running it twice silently inserts duplicates.  For re-runs after
# the database exists, use the upsert/refresh cell below instead.
vector_store = Chroma(
    collection_name="document_collection_1",
    embedding_function=OpenAIEmbeddings(),
    persist_directory="./chroma_db"
)

# Add chunks to Chroma db
vector_store.add_documents(clean_chunks)

print("Embeddings stored in ./chroma_db")

Embeddings stored in ./chroma_db

In [ ]:
## OPTIONAL STEP — Refresh and upsert Chroma DB
# Use this cell to synchronize your Vector Store with the new chunks.
# This approach ensures version consistency and prevents "ghost chunks" from old files.

# Set to True to wipe all existing chunks for a 'source' before inserting the new version.
# Set to False for a pure upsert (only updates chunks with identical chunk_hash_id).
REFRESH_EXISTING_SOURCES = True

# Initialize the Chroma vector store
vector_store = Chroma(
    collection_name="document_collection_1",
    embedding_function=OpenAIEmbeddings(),
    persist_directory="./chroma_db"
)

# Prepare batch data for the database
# Use pre-calculated chunk_hash_id as the primary database ID for deterministic lookups.
ids = [chunk.metadata.get("chunk_hash_id") for chunk in clean_chunks]
documents = [chunk.page_content for chunk in clean_chunks]
metadatas = [chunk.metadata for chunk in clean_chunks]

# Generate embeddings for the current batch
embeddings = OpenAIEmbeddings().embed_documents(documents)

# --- SOURCE-LEVEL CLEANUP ---
# If enabled, we remove all previous chunks belonging to the files in this batch.
# This is critical if the new file version has fewer chunks than the old version.
if REFRESH_EXISTING_SOURCES:
    
    # Identify unique filenames (sources) in the current batch to refresh.
    # The Set {} removes duplicates so we only perform one delete per document.
    sources_to_refresh = sorted({m.get("source") for m in metadatas if m.get("source")})
    
    # Iterate through each unique source and purge old data.
    # This matches the 'source' metadata field stored in Chroma.
    for source in sources_to_refresh:
        # Deletes all chunks associated with this file source
        vector_store._collection.delete(where={"source": source})
    
    print(f"Chroma DB: Purged existing chunks for {len(sources_to_refresh)} source(s)")


# --- UPSERT DATA ---
# We use _collection.upsert to either insert new chunks or update existing ones.
# Because we provide specific IDs (chunk_hash_id), we avoid creating duplicates.
vector_store._collection.upsert(
    ids=ids,
    documents=documents,
    embeddings=embeddings,
    metadatas=metadatas
)

print(f"Chroma DB: Successfully upserted {len(clean_chunks)} chunks.")

In [27]:
# Initiate FTS and index chunks — first-time setup only.
# `add_documents` is append-only and does not dedupe; running this cell
# twice silently inserts duplicate rows.  For re-runs after the index
# exists, use the update/refresh cell below instead.
fts_store = FTSStore()
fts_store.add_documents(clean_chunks)

print("Indexing complete")

Indexing complete

In [ ]:
## OPTIONAL STEP — UPDATE SQLite FTS (delete + re-index)
# Use this cell to synchronize the SQLite Full-Text Search (FTS) index with the new chunks.
# It ensures that only the latest version of each document exists in the database.

# Set to True to perform a "Wipe and Replace" for every file in the current batch.
# Set to False to skip existing files and only add brand-new ones.
REFRESH_EXISTING_SOURCES = True

# Initialize or connect to the FTS storage
fts_store = FTSStore()

# Get sorted set with unique source values from the new chunks 
sources_to_refresh = sorted({m.get("source") for m in [c.metadata for c in clean_chunks] if m.get("source")})

if REFRESH_EXISTING_SOURCES:
    """
    Perform a Source-Level Refresh:
    1. Iterates through each unique source in the new batch.
    2. Deletes all existing rows in SQLite matching that source.
       - This prevents 'ghost' chunks if the new file version is shorter than the old one.
    3. Re-inserts the fresh chunks with updated content and metadata (like doc_hash_id).
    """

    for source in sources_to_refresh:
        fts_store.cur.execute("DELETE FROM docs WHERE source = ?", (source,))
    
    fts_store.conn.commit()
    print(f"SQLite FTS: Purged existing rows for {len(sources_to_refresh)} source(s)")

    fts_store.add_documents(clean_chunks)
    print(f"SQLite FTS: Re-indexed {len(clean_chunks)} chunks.")

else:
    """
    Perform an Append-Only Update:
    1. Fetches a list of all sources already present in the database.
    2. Filters the current batch to find chunks from completely new files.
    3. Only inserts chunks that don't have a matching source in the DB.
    """

    fts_store.cur.execute("SELECT DISTINCT source FROM docs")
    indexed_sources = {row[0] for row in fts_store.cur.fetchall()}
    
    new_chunks = [c for c in clean_chunks if c.metadata.get("source") not in indexed_sources]
    if new_chunks:
        fts_store.add_documents(new_chunks)
        print(f"SQLite FTS: Added {len(new_chunks)} chunks from new sources.")
    else:
        print("SQLite FTS: All sources already indexed. No new chunks added.")

### CHECK DOCUMENTS, CHUNKS, AND METADATA

In [ ]:
# View what is stored in persisted vector store
vector_store = Chroma(
    collection_name="document_collection_1",
    embedding_function=OpenAIEmbeddings(),
    persist_directory="./chroma_db"
)

print(vector_store.get())

In [ ]:
# Print chunk metadata
for i, chunk in enumerate(clean_chunks):
    print(chunk.metadata)

In [ ]:
# Print and inspect metadata
collection = vector_store._collection
data = collection.get(include=["embeddings", "documents", "metadatas"])

print(f"Number of chunks: {len(data['documents'])}\n")

for i in range(len(data["documents"])):
    print("ID:", data["ids"][i])
    print("TEXT:", data["documents"][i])
    print("METADATA:", data["metadatas"][i])
    print("VECTOR (first 5 dims):", data["embeddings"][i][:5])
    print("-"*40)

In [ ]:
# Test retrieval, metadata
results = vector_store.similarity_search("your query", k=1)

for result in results:
    print(result.page_content)
    print(result.metadata)

In [ ]:
# Reduce embeddings to 2-D with PCA and scatter-plot them by category.
# Useful for a visual sanity check that semantically similar chunks
# cluster together in embedding space.
data = collection.get(include=["embeddings", "metadatas"])
embeddings = np.array(data["embeddings"])
categories = [m.get("category", "unknown") for m in data["metadatas"]]

pca = PCA(n_components=2)
reduced = pca.fit_transform(embeddings)

fig, ax = plt.subplots(figsize=(8, 6))
for category in sorted(set(categories)):
    mask = [c == category for c in categories]
    ax.scatter(reduced[mask, 0], reduced[mask, 1], label=category, alpha=0.7)

ax.set_xlabel("PC 1")
ax.set_ylabel("PC 2")
ax.set_title("Chunk embeddings (PCA → 2D), coloured by category")
ax.legend()
plt.tight_layout()
plt.show()